declare module "remark";
declare module "remark-math";
declare module "remark-highlight.js";
declare module "remark-highlight.js";
declare module "remark-breaks";
declare module "remark-html";
declare module "remark-html-katex";
declare module "comlinkjs";
declare module "prettier/*";
